In [3]:
import torch

In [4]:
my_torch=torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
#Reshape and View
my_torch=my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

## Rehshape with -1

In [10]:
#resape if we dont know the number of items using -1
my_torch2=torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
my_torch2=my_torch2.reshape(3,-1) # assuming we dont know that the value is 15 how do we determine how many rows to columns to create so we use -1
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

## Reshape v View
The main difference is that view() requires the tensor's underlying memory to be contiguous, while reshape() is more flexible and will automatically create a copy if the memory is not contiguous. 

In [14]:
my_torch3=torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
my_torch4=my_torch.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
# Reshape and view will update 
my_torch5=torch.arange(10)
my_torch5

my_torch6=my_torch5.reshape(2,5)
my_torch6

my_torch5[1]=4141
my_torch5


tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [19]:
my_torch6
#as you can see changing value is torch5 also updates torch 6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

## Slices

In [22]:
my_torch7=torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
my_torch7[7]

tensor(7)

In [35]:
#grab a slice
my_torch8=my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [36]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [37]:
#the problem with the above is that it return a list what if we want to maintain the column shape
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])